# Generated by Django 6.0.4 on 2026-04-10 00:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_alter_maliciousbot_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='maliciousbot',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AddField(
            model_name='maliciousbot',
            name='confidence',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='maliciousbot',
            name='prediction',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='maliciousbot',
            name='prediction_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='maliciousbot',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='maliciousbot',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='maliciousbot',
            name='bot',
            field=models.CharField(blank=True, max_length=90, null=True),
        ),
    ]
